### PR TITLE
Added ability to define transition type when defining route

### PR DESCRIPTION
**Pull request by jonsamwell**
Also updated the test dependency in pubspec.yaml.

This is just a first pass to get your thoughts...

It should cover the enhancements needed for https://github.com/theyakka/fluro/issues/27

### CODE REVIEW

**Comment by jonsamwell** [comment]
Any update on this?

**Comment by lukef** [comment]
There are a couple of things:

1. It looks to be broken. I just ran the example app and the transitions are all executing the "native" transition. 
2. Any transition passed via `navigateTo` should **always** take priority over anything defined at the route level (doesn't seem the case now)

I think there are a few other changes needed until this can be merged. For example: You will probably want to eliminate the default on the optional transition for `navigateTo` and check for null later otherwise you wont be able to test to see if it has been set to override.

You probably also want to make transition optional on the route with null as the default value.

**Comment by lukef** [comment]
I've done all the fixes but i need you to add me as a collaborator in order to push them to your fork

**Comment by jonsamwell** [comment]
@lukef You branch looks good many thanks.  I'll clone it and test.

**Comment by lukef** [comment]
Let me know when you think it's ready and I'll smoke test and we can be good to go.

**Comment by gedw99** [comment]
Thanks all !

**Comment by jonsamwell** [comment]
@lukef I'm really sorry for the insane delay getting back to you!

I've just had a play with your changes for this and it is working really well.  Thanks gain for the changes.

I realize this is a couple of releases behind the main repo so let me know if you want me to do a PR to update your fork of this so we can merge.

Thanks again!

**Comment by Benoss** [comment]
This look awesome, can we get a release with that?

**Comment by jonsamwell** [comment]
@Benoss it is awesome!  I'm just waiting on @lukef to see if he wants me to update his fork of this PR so it can be merged into the main branch without any conflicts.

**Comment by lukef** [comment]
If you can resolve the conflicts I'll do a release

**Comment by jonsamwell** [comment]
@lukef this PR is now updated from your working fork and the changes from master have also been merged in.  I also added a line to the readme file to indicate how to specify a route transition when defining a route. Hopefully this is good to now 👍

**Comment by jonsamwell** [comment]
@lukef any chance we can get this merged in and released?

**Comment by lukef** [comment]
1.4.0 is published

**Pull request merged**
